[window]
opacity = 1.0
padding.x = 10
padding.y = 10
decorations = "Full"
decorations_theme_variant = "Dark"

[font]
normal.family = "IBM Plex Mono"
bold.family = "IBM Plex Mono"
italic.family = "IBM Plex Mono"
bold_italic.family = "IBM Plex Mono"
size = 11.0

# Primary colors
[colors.primary]
background = '#252E25'   # bg_primary
foreground = '#EAE6D5'   # fg_primary

# Normal ANSI colors
[colors.normal]
black   = '#1A211A'      # bg_inactive (dim black)
red     = '#F1735D'      # error strong
green   = '#A3C9A9'      # green soft
yellow  = '#E7B77A'      # orange soft / warm yellow
blue    = '#AAC0C9'      # soft blue
magenta = '#C2B2D1'      # soft purple
cyan    = '#A2D1CC'      # soft cyan
white   = '#EAE6D5'      # fg_primary

# Bright ANSI colors
[colors.bright]
black   = '#4A5A49'      # selection (slightly lifted)
red     = '#E3947D'      # soft red
green   = '#C3D9B7'      # soft lifted green (function color)
yellow  = '#ECD2A5'      # soft yellow
blue    = '#C7D6DD'      # lighter blue
magenta = '#D8C9E2'      # lighter lavender
cyan    = '#BEE1DD'      # lighter soft cyan
white   = '#F5F2E7'      # slightly brighter ivory
