[window]

opacity = 1.0

padding.x = 10
padding.y = 10

decorations = "Full"
decorations_theme_variant = "Dark"

[font]

normal.family = "IBM Plex Mono"
bold.family = "IBM Plex Mono"
italic.family = "IBM Plex Mono"
bold_italic.family = "IBM Plex Mono"

size = 11.0

# Default colors
[colors.primary]
background = '#1B241B'
foreground = '#E8E3D1'

# Normal colors
[colors.normal]
black   = '#1B241B'
red     = '#E17860'
green   = '#98C5A0'
yellow  = '#E5C287'
blue    = '#9AAFB8'
magenta = '#D4A8B8'
cyan    = '#9BC9C3'
white   = '#E8E3D1'

# Bright colors
[colors.bright]
black   = '#5C705E'
red     = '#E16C5B'
green   = '#78A67E'
yellow  = '#FFD67C'
blue    = '#B8C7AF'
magenta = '#E8C48F'
cyan    = '#9FAA88'
white   = '#E6E1CF'

[keyboard]
[[keyboard.bindings]]
key = "X"
mods = "Control"
action = "Copy"

[[keyboard.bindings]]
key = "V"
mods = "Control"
action = "Paste"
